title: Sean's Github web project Jan 10 2021
author: Shaun
email: swoeanf@GMAIL.COM
description: > # this means to ignore newlines until "baseurl:"
  awesome description here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
